### ISSUE TITLE
doesn't actually watch for button presses

### ISSUE THREAD

**Issue by timball** [hortinstein/node-dash-button#13]
what it does is listen for arps. which detects when button wakes up and connects to wireless network. 

aka multiple button presses will NOT result in multiple "actions" within the same wifi connectivity session. 

something to do, maybe, is arp cache poison and fake https endpoint. but this will more than likely interfere w/ legitimate buttons.

--timball

**Comment by hortinstein** [comment]
Right, that is clearly stated in the README.  The ARP poisoning is an interesting idea though!
