### ISSUE TITLE
Merging continuous arp requests

### ISSUE THREAD

**Issue by gerardo-navarro** [hortinstein/node-dash-button#16]
Hi Guys,

first of all. Thank you very much for this awesome package. You make it easy to play around with the dash button. Nice job.

However, once I press the dash button, my app registers to two continuous request. I know that you mention this in the documentation. But, I was wondering if there is a way to merge the two requests which originate from one button press?

Thanks for the help.

Gerardo

**Comment by hortinstein** [comment]
try adjusting the timeout code on line 73 of ```index.js``` if your network is still registering multiple presses after 3 seconds: ```setTimeout(function () { just_emitted = false; }, 3000);```.  If that doesn't work you can handle it in your code by adjusting a just pressed flag

**Comment by ecaron** [comment]
I was experiencing this, too. I think my PR (#18) fixes this.

**Comment by hortinstein** [comment]
Thank you, the pull request is merged!  Please let me know if anyone else continues to have this issue
