### ISSUE TITLE
Amazon iOS app push notifications

### ISSUE THREAD

**Issue by dankantor** [hortinstein/node-dash-button#17]
This works great! Thanks so much for it. One thing I am seeing is every time I push the button, my Amazon iOS app shows a push notification:

```
Your Huggies Dash Button is almost ready for use. Finish the setup process to use your Dash Button
```

I know it may be out of scope for this project but I'm wondering if you anyone else gets these messages and if there is any way to suppress them?

**Comment by ecaron** [comment]
You have to go into the app and under Your Account -> Manage Dash Devices go into Notifications and turn everything off.

**Comment by hortinstein** [comment]
closing issue, thanks for the answer ecaron

**Comment by dankantor** [comment]
Thanks guys.
