### ISSUE TITLE
Support for Node 5.4 or 4.0?

### ISSUE THREAD

**Issue by Connor-Knabe** [hortinstein/node-dash-button#19]
It seems to be running fine on OSX which is v0.10.32 but on my Raspberry Pi 2 and Zero which are running 5.4 and 4.0 respectively it doesn't seem to run.

Typing in node bin/findbutton shows nothing and running the app (using sudo) just exits with no error on Pi Zero running v5.4 and gives me "/node_modules/pcap/build/Release/pcap_binding.node: invalid ELF header" on my Pi 2 running v4.0

**Comment by hortinstein** [comment]
hmmm, the invalid ELF header is usually related to the compilation of a shared library.  It appears there are some compilation issues with node-pcap for that platform.

Can you try to remove your ~~~node_modules~~~ folder and reinstall with ```npm install```

**Comment by Connor-Knabe** [comment]
@hortinstein Yeah it seems to not give this error now however running findbutton doesn't seem to print anything out not even the console.log that is in there.  Is there a way to check if my WiFi device (cannakit WiFi dongle) can do promiscuous mode?

**Comment by Connor-Knabe** [comment]
@hortinstein I believe it was the WiFi adapter. Have it working on my Pi with Node 4.0 on it. Thanks!
