### ISSUE TITLE
Cannot choose interface which to listen to ARP

### ISSUE THREAD

**Issue by bfrantz** [hortinstein/node-dash-button#20]
On devices with multiple interfaces node_pcap uses a "default" interface which is not necessarily the one you want.  It would be useful to be able to pass the desired interface using 

```javascript
var pcap = require('pcap'),
    pcap_session = pcap.createSession(interface, filter);

**Comment by hortinstein** [comment]
Thanks for the #21 it has been merged and updated to NPM
