### ISSUE TITLE
Find button detects but when in a script it does not

### ISSUE THREAD

**Issue by tvl83** [hortinstein/node-dash-button#25]
I had this working yesterday perfectly fine and I tried to bring the dash to another network and had annoying problems with that. Moving a dash to another network is kind of stupid. You cannot just connect to the config options and change the network, apparently. You have to deactivate it from your amazon account and add it on the other network.

I have the amazon successfully back on my network (I had issues getting it BACK on my network last night). The findbutton script successfully sees the arp packets and the dashes, but when I run my node app with `sudo npm start` it has many of those `node_pcap: EthernetFrame() : Don't know how to decode ethertype ` messages when I press the button but it does not detect my buttons or any other ARP packets.

Are there any known issues about this?

**Comment by tvl83** [comment]
Completely my fault. I was trying to detect the button pushes but I had it in an io.on('connection') because i am using socket.io. I was not refreshing the page to make a connection to wireup the detected code.

**Comment by hortinstein** [comment]
good to hear! thx man
