### ISSUE TITLE
Dash button "detected" event is called multiple times for a single press

### ISSUE THREAD

**Issue by nuudles** [hortinstein/node-dash-button#27]
Recently, I've noticed that my "detected" callback is being called multiple times for a single press. Our button is hooked up to a script to toggle the lights, so pressing the button to turn off the light inevitably has the light turn on after a minute or so. Has something change with the detection mechanism? Could the button be sending multiple ARP packets?

```javascript
dash.on("detected", function (){
        toggleLight();
});
```

**Comment by hortinstein** [comment]
yeah, there is a rate limiting thing within the script on line ```63``` in ```index.js```

```setTimeout(function () { just_emitted[mac_address] = false; }, 3000);```

Try adjusting 3000 if it is firing multiple times.  I would be willing to make this an optional variable during init

**Comment by hortinstein** [comment]
Since I received several reports of the timeout not being enough, I made it adjustable and upped the default to 5 seconds.  Please see pull request #29  

Once it is on NPM i am closing this.  It is non-breaking for existing code

**Comment by nuudles** [comment]
@hortinstein As an FYI, I had to up mine up to a full minute to debounce the signal. Even 30 seconds didn't cut it.
