### ISSUE TITLE
PR #23 not in latest version

### ISSUE THREAD

**Issue by dangothemango** [hortinstein/node-dash-button#28]
Hey,

Im currently working on expanding and improving the pizzadash project which uses this as a dependency. I just fixed a bug using the same solution as in error [#14](https://github.com/hortinstein/node-dash-button/issues/14). Id like for the users to just use npm install but that does not yet include PR [#23](https://github.com/hortinstein/node-dash-button/pull/23) so the error will still exist. Could you increment the version number and push to npm?

Dan

**Comment by hortinstein** [comment]
Yeah I will take care of it after work

**Comment by dangothemango** [comment]
awesome, thank you

**Comment by hortinstein** [comment]
taken care of!  Thanks!
