### ISSUE TITLE
any idea what dependancy i am missing here?

### ISSUE THREAD

**Issue by stoneobscurity** [hortinstein/node-dash-button#30]
root@norah:/home/stone# npm install node-dash-button 
npm http GET https://registry.npmjs.org/node-dash-button
npm http 304 https://registry.npmjs.org/node-dash-button
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/socketwatcher
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/socketwatcher
npm WARN engine socketwatcher@0.3.0: wanted: {"node":">=4"} (current: {"node":"v0.10.25","npm":"1.3.10"})

> socketwatcher@0.3.0 install /home/stone/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.2.0-27-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/stone/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by fwertz** [comment]
`This failure might be due to the use of legacy binary "node"`. Update to at least Node `4.2.1`. Currently `4.4.4` is listed at LTS.

**Comment by hortinstein** [comment]
what version of npm were you trying?

**Comment by stoneobscurity** [comment]
this is a fresh install of ubuntu 15.04 (vm) and i was using apt-get install nodejs

**Comment by hortinstein** [comment]
install node from source, should fix the problem or use nvm or n to update
node
