### ISSUE TITLE
Still getting notifications on android phone

### ISSUE THREAD

**Issue by jinpark** [hortinstein/node-dash-button#31]
Hello, I just went through the setup process and made a quick test to make sure my dash button works with this library. (It does, and thank you!)

I'm just wondering if I'm supposed to be getting this notification on my android phone where I did the initial setup with the Amazon Shopping app  every time I press the dash button with the node-dash-button server.

```
Your ______ Dash Button is almost ready for use. Finish the setup process to use your Dash Button.
```

Is there a way I can prevent the dash button from getting through to the phone?

**Comment by cnandreu** [comment]
You can disable notifications using the mobile app.

Settings > "Notification Settings" under "Your dash buttons"  > Set "Dash Button Updates" to "off".

[Source and pictures showing the steps here](https://davekz.com/hacking-amazon-dash-buttons/)

**Comment by jinpark** [comment]
Bah, I'm an idiot. Thanks a lot!
