### ISSUE TITLE
Amazon IoT dash button triggers twice

### ISSUE THREAD

**Issue by grosen** [hortinstein/node-dash-button#43]

**Comment by kclack** [comment]
The 3rd value in the dash_button() function is the timeout for looking for requests after the last press.  By default, it is set to 5 seconds.  After finding out how long it is before another trigger happens on your network, I'd recommend setting the timeout a little higher.  From the readme, here is it set for 1 minute (value is in milliseconds) 

var dash = dash_button("your:dash:mac", null, 60000, 'all');

**Comment by hortinstein** [comment]
Thanks
