### ISSUE TITLE
error installing on raspberry pi

### ISSUE THREAD

**Issue by fredfred41** [hortinstein/node-dash-button#49]
Hi, 
Like I said in previous post a friend gave me raspberry pi ( first version), I  m a noob in linux, but I succed booting up the pi, enabling ssh, installing npm and libpcap... But when I try to install your code : npm install node-dash-button , I have a this error,  : 

pi@raspberrypi:~ $ npm install node-dash-button
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:72:28)
npm WARN addRemoteGit     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:75:29)
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:83:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:95:15)
npm WARN addRemoteGit  git+https://github.com/mranney/node_pcap.git resetting remote /home/pi/.npm/_git-remotes/https-github-com-mranney-node-pcap-git-72c55299 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror https://github.com/mranney/node_pcap.git /home/pi/.npm/_git-remotes/https-github-com-mranney-node-pcap-git-72c55299: undefined
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror https://github.com/mranney/node_pcap.git /home/pi/.npm/_git-remotes/https-github-com-mranney-node-pcap-git-72c55299: undefined
npm ERR! Linux 4.4.34+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-dash-button"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

some help would be really appreciate, thanks

**Comment by hortinstein** [comment]
Looks like you just need to install git... On rasberrian

sudo apt-get install git

Also good idea to update npm and node
