### ISSUE TITLE
Can't maintain a solidified connection

### ISSUE THREAD

**Issue by bhberson** [hortinstein/node-dash-button#6]
Here is output of running an app consistently for a handful of minutes. My first though is that the server looses connectivity to the network due to WiFi issues or something and then it can't gracefully recover, you have to reboot the app to get it working again.
```
master => ~/GitHub/pizzadash/ npm start

> pizzadash@1.0.0 start /Users/brodyberson/GitHub/pizzadash
> sudo node app.js

node_pcap: EthernetFrame() - Don't know how to decode ethertype 34958
node_pcap: EthernetFrame() - Don't know how to decode ethertype 34958
node_pcap: EthernetFrame() - Don't know how to decode ethertype 34958
node_pcap: EthernetFrame() - Don't know how to decode ethertype 34958
```

**Comment by hortinstein** [comment]
Thanks, I will try to replicate this.

**Comment by hortinstein** [comment]
I have not been able to replicate this, but thought of a solution to periodically reset the pcap capture session if it is not responding.  I will try to implement it in a branch to see if I can cause a reinit of the pcap session that might alleviate it.

**Comment by ecaron** [comment]
This error just appears to be pcap being a bit noisy in its output to console.log, and doesn't actually reflect any broken functionality.

I opened a PR in node_pcap (https://github.com/mranney/node_pcap/pull/195) and once/if that gets merged then I'll submit a smaller PR for node-dash-button to silence pcap's output.
