### ISSUE TITLE
npm install fails while compiling cpp sources

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [hortinstein/node-dash-button#63]
I have a archlinux installation, all packages up-to-date,
and I cannot install node-dash-button from npm repo or github source checkout.

Is there any dependency outdated?

please see attached compile log output:

    $ LC_ALL=C npm install node-dash-button 2>&1 | tee install.log
<details>

    > socketwatcher@0.3.0 install /home/feedc0de/dashbuttons/node_modules/socketwatcher
    > node-gyp rebuild

    make: Entering directory '/home/feedc0de/dashbuttons/node_modules/socketwatcher/build'
      CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
    In file included from ../socket_watcher.hpp:8,
                     from ../socket_watcher.cpp:5:
    ../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
    ../../nan/nan.h:2298:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
     2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
          |                                                              ^
    ../socket_watcher.cpp: In static member function 'static void SocketWatcher::Initialize(v8::Local<v8::Object>)':
    ../socket_watcher.cpp:29:36: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
       29 |   constructor.Reset(t->GetFunction());
          |                                    ^
    In file included from /home/feedc0de/.cache/node-gyp/12.12.0/include/node/node.h:63,
                     from ../../nan/nan.h:54,
                     from ../socket_watcher.hpp:8,
                     from ../socket_watcher.cpp:5:
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/v8.h:5995:46: note: candidate: 'v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)'
     5995 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
          |                                              ^~~~~~~~~~~
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/v8.h:5995:46: note:   candidate expects 1 argument, 0 provided
    ../socket_watcher.cpp:30:75: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
       30 |   exports->Set(Nan::New("SocketWatcher").ToLocalChecked(), t->GetFunction());
          |                                                                           ^
    In file included from /home/feedc0de/.cache/node-gyp/12.12.0/include/node/node.h:63,
                     from ../../nan/nan.h:54,
                     from ../socket_watcher.hpp:8,
                     from ../socket_watcher.cpp:5:
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/v8.h:5995:46: note: candidate: 'v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)'
     5995 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
          |                                              ^~~~~~~~~~~
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/v8.h:5995:46: note:   candidate expects 1 argument, 0 provided
    ../socket_watcher.cpp: In static member function 'static void SocketWatcher::Callback(uv_poll_t*, int, int)':
    ../socket_watcher.cpp:77:60: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
       77 |   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
          |                                                            ^
    In file included from ../socket_watcher.hpp:8,
                     from ../socket_watcher.cpp:5:
    ../../nan/nan.h:1024:46: note: declared here
     1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
          |                                              ^~~~~~~~~~~~
    ../socket_watcher.cpp:77:60: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
       77 |   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
          |                                                            ^
    In file included from ../socket_watcher.hpp:8,
                     from ../socket_watcher.cpp:5:
    ../../nan/nan.h:1024:46: note: declared here
     1024 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
          |                                              ^~~~~~~~~~~~
    ../socket_watcher.cpp: In static member function 'static void SocketWatcher::Set(const Nan::FunctionCallbackInfo<v8::Value>&)':
    ../socket_watcher.cpp:116:32: error: no matching function for call to 'v8::Value::Int32Value()'
      116 |   int fd = info[0]->Int32Value();
          |                                ^
    In file included from /home/feedc0de/.cache/node-gyp/12.12.0/include/node/node.h:63,
                     from ../../nan/nan.h:54,
                     from ../socket_watcher.hpp:8,
                     from ../socket_watcher.cpp:5:
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/v8.h:2613:40: note: candidate: 'v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const'
     2613 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
          |                                        ^~~~~~~~~~
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
    In file included from ../../nan/nan.h:54,
                     from ../socket_watcher.hpp:8,
                     from ../socket_watcher.cpp:5:
    ../socket_watcher.cpp: At global scope:
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/node.h:560:43: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
      560 |       (node::addon_register_func) (regfunc),                          \
          |                                           ^
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/node.h:594:3: note: in expansion of macro 'NODE_MODULE_X'
      594 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
          |   ^~~~~~~~~~~~~
    ../socket_watcher.cpp:143:1: note: in expansion of macro 'NODE_MODULE'
      143 | NODE_MODULE(socketwatcher, Init)
          | ^~~~~~~~~~~
    In file included from /home/feedc0de/.cache/node-gyp/12.12.0/include/node/node.h:63,
                     from ../../nan/nan.h:54,
                     from ../socket_watcher.hpp:8,
                     from ../socket_watcher.cpp:5:
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/node_object_wrap.h:84:78:   required from here
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/v8.h:10004:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
    10004 |                reinterpret_cast<Callback>(callback), type);
          |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
    ../../nan/nan_object_wrap.h:65:61:   required from here
    /home/feedc0de/.cache/node-gyp/12.12.0/include/node/v8.h:10004:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
    make: *** [socketwatcher.target.mk:105: Release/obj.target/socketwatcher/socket_watcher.o] Error 1
    make: Leaving directory '/home/feedc0de/dashbuttons/node_modules/socketwatcher/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    gyp ERR! System Linux 5.3.5-arch1-1-ARCH
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/feedc0de/dashbuttons/node_modules/socketwatcher
    gyp ERR! node -v v12.12.0
    gyp ERR! node-gyp -v v6.0.0
    gyp ERR! not ok 
    npm WARN enoent ENOENT: no such file or directory, open '/home/feedc0de/dashbuttons/package.json'
    npm WARN dashbuttons No description
    npm WARN dashbuttons No repository field.
    npm WARN dashbuttons No README data
    npm WARN dashbuttons No license field.

    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! socketwatcher@0.3.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the socketwatcher@0.3.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/feedc0de/.npm/_logs/2019-10-14T21_59_31_630Z-debug.log
</details>

**Comment by dominick-han** [comment]
How did you solve it?
